version: '3.8'

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "coop@user"
      POSTGRES_PASSWORD: "coop@password"
      POSTGRES_DB: "coop_decision_hub"
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
