CREATE TABLE sessao_votacao
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pauta_id             BIGINT,
    fechada              BOOLEAN                                 NOT NULL,
    data_fechamento_real TIMESTAMP WITHOUT TIME ZONE,
    data_abertura        TIMESTAMP WITHOUT TIME ZONE,
    data_fechamento      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sessaovotacao PRIMARY KEY (id)
);

ALTER TABLE sessao_votacao
    ADD CONSTRAINT FK_SESSAOVOTACAO_ON_PAUTA FOREIGN KEY (pauta_id) REFERENCES pauta (id);