CREATE TABLE voto
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sessao_votacao_id BIGINT,
    associado_id      BIGINT,
    voto              BOOLEAN,
    CONSTRAINT pk_voto PRIMARY KEY (id)
);

ALTER TABLE voto
    ADD CONSTRAINT FK_VOTO_ON_SESSAO_VOTACAO FOREIGN KEY (sessao_votacao_id) REFERENCES sessao_votacao (id);